# Generated by Django 4.1 on 2022-09-11 13:04

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(default='', upload_to='Blog')),
                ('posttime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='employee_database',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter the 10 digit number', regex='^[0-9]{10}$')])),
                ('date_of_birth', models.DateField(help_text='Date format: YYYY-MM-DD', max_length=11)),
                ('job_profile', models.CharField(max_length=150)),
                ('report_manager', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(default='', upload_to='user_profile')),
                ('gender', models.CharField(choices=[('select', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Others')], default='Select', max_length=15)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'register_data',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
